apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "talent"
  name: "talent"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "talent"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "talent"
    spec:
      containers:
        - image: 886617140000.dkr.ecr.us-east-1.amazonaws.com/talent:0.1
          imagePullPolicy: IfNotPresent
          name: "talent"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
